import type { PolicySource } from "@/types/iimb-ug";

export const IIMB_UG_SOURCES: PolicySource[] = [
  {
    id: "iimb-ug-2027-procedure",
    title: "IIMB UG Admission Procedure 2027–31",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/wp-content/uploads/2026/08/UG-Admissions-Process_2026.pdf",
    cycle: "2027-31",
    sourceType: "OFFICIAL_CURRENT",
    verifiedAt: "2026-08-29",
    supports: [
      "programmes",
      "age",
      "Class X overall eligibility",
      "Mathematics XI/XII",
      "test structure",
      "positive sectional gate",
      "historical first-shortlist table",
      "pre-PI weights",
      "post-PI weights",
      "references",
      "reservation statement",
    ],
    notes: "Formal cycle-specific admission procedure. It does not publish UG raw-to-weighted transformations, normalization statistics, current shortlist thresholds or programme closing scores.",
  },
  {
    id: "iimb-ug-2027-faq",
    title: "IIMB UG Admissions FAQ — Test 2026",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/wp-content/uploads/2026/08/UG-Admissions-FAQ-2026.pdf",
    cycle: "2027-31",
    sourceType: "OFFICIAL_CURRENT",
    verifiedAt: "2026-08-29",
    supports: [
      "dates",
      "age",
      "Class X Mathematics eligibility",
      "Mathematics XI/XII",
      "test duration",
      "negative marking",
      "programme preference",
      "single common interview",
    ],
    notes: "Conflicts with the formal procedure on whether the 60% Class X requirement is overall or Mathematics-specific.",
  },
  {
    id: "iimb-ug-2027-dates",
    title: "UG Admissions 2027",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/ug-admissions-2027/",
    cycle: "2027-31",
    sourceType: "OFFICIAL_CURRENT",
    verifiedAt: "2026-08-29",
    supports: ["application window", "test date", "interview window", "offer window"],
  },
  {
    id: "iimb-ug-2026-faq-historical",
    title: "IIMB UG Programmes FAQ — inaugural cycle",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/wp-content/uploads/2025/10/UG-Programmes-FAQs.pdf",
    cycle: "2026-30",
    sourceType: "OFFICIAL_HISTORICAL",
    verifiedAt: "2026-08-29",
    supports: ["historical 120-minute format", "historical 60/40 final structure", "programme intake"],
    notes: "Historical only. Its 120-minute test and 60% test / 40% PI final structure must never overwrite 2027–31 rules.",
  },
  {
    id: "iimb-pgp-standardisation-analogue",
    title: "IIMB PGP Admission Process",
    institution: "IIM Bangalore",
    url: "https://www.iimb.ac.in/admissions/pgp-admissions/admission-process",
    cycle: "PGP 2026-28",
    sourceType: "OFFICIAL_ANALOGUE",
    verifiedAt: "2026-08-29",
    supports: ["bounded mean/SD standardisation analogue"],
    notes: "Official for PGP only. UG use is not confirmed.",
  },
];

export const IIMB_UG_ASSUMPTIONS = [
  "The formal 2027 procedure and current FAQ conflict on whether the 60% Class X rule applies to overall marks or Mathematics marks.",
  "Canonical +3/−1 scores are an exact three-times representation of the confirmed +1/−1/3 marking scheme.",
  "The historical table's aggregate 114 is treated as a canonical raw-score floor because it cannot be a percentile.",
  "Linear raw-to-weighted test conversion is a transparent planning model, not IIMB's confirmed conversion.",
  "The PGP mean/SD standardisation formula is an official analogue only; UG normalization is not published.",
  "Gender-diversity eligibility is not inferred from the selected gender.",
  "The current interview-call cutoff is unknown.",
  "The current final composite cutoff is unknown.",
  "Programme-level closing scores and allocation data are unknown.",
  "Admission probability remains disabled until defensible multi-cycle calibration data exists.",
] as const;

