import type { PolicySource } from "@/types/iimb-ug";

export const IIMB_UG_SOURCES: PolicySource[] = [
  {
    id: "iimb-ug-2027-procedure",
    title: "IIMB UG Admission Procedure 2027–31",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/wp-content/uploads/2026/09/UG_Admissions_Process-2026.pdf",
    cycle: "2027-31",
    sourceType: "OFFICIAL_CURRENT",
    verifiedAt: "2026-08-29",
    supports: [
      "programmes",
      "age",
      "Class X overall eligibility",
      "Mathematics XI/XII",
      "test structure",
      "positive sectional gate",
      "historical first-shortlist table",
      "pre-PI weights",
      "post-PI weights",
      "references",
      "reservation statement",
    ],
    notes: "Formal cycle-specific admission procedure. It does not publish UG raw-to-weighted transformations, normalization statistics or current shortlist thresholds.",
  },
  {
    id: "iimb-ug-data-sciences-programme",
    title: "IIMB UG Data Sciences Programme Eligibility",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/programmes/bsc-honours-data-sciences/",
    cycle: "2027-31",
    sourceType: "OFFICIAL_CURRENT",
    verifiedAt: "2026-09-17",
    supports: [
      "Class X Mathematics eligibility",
    ],
    notes: "Programme page specifies at least 60% in Class X Mathematics. The cycle-specific procedure instead says at least 60% in Class X without naming the subject.",
  },
  {
    id: "iimb-ug-economics-programme",
    title: "IIMB UG Economics Programme Eligibility",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/programmes/bsc-economics/",
    cycle: "2027-31",
    sourceType: "OFFICIAL_CURRENT",
    verifiedAt: "2026-09-17",
    supports: ["Class X Mathematics eligibility"],
    notes: "Programme page also specifies at least 60% in Class X Mathematics.",
  },
  {
    id: "iimb-ug-2027-dates",
    title: "UG Admissions 2027",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/ug-admissions-2027/",
    cycle: "2027-31",
    sourceType: "OFFICIAL_CURRENT",
    verifiedAt: "2026-08-29",
    supports: ["application window", "test date", "interview window", "offer window"],
  },
  {
    id: "iimb-ug-2026-faq-historical",
    title: "IIMB UG Programmes FAQ — inaugural cycle",
    institution: "IIM Bangalore",
    url: "https://ug.iimb.ac.in/wp-content/uploads/2025/10/UG-Programmes-FAQs.pdf",
    cycle: "2026-30",
    sourceType: "OFFICIAL_HISTORICAL",
    verifiedAt: "2026-08-29",
    supports: ["historical 120-minute format", "historical 60/40 final structure", "programme intake"],
    notes: "Historical only. Its first-shortlist conditions are used for context and must never overwrite 2027–31 rules.",
  },
  {
    id: "iimb-pgp-standardisation-analogue",
    title: "IIMB PGP Admission Process",
    institution: "IIM Bangalore",
    url: "https://www.iimb.ac.in/admissions/pgp-admissions/admission-process",
    cycle: "PGP 2026-28",
    sourceType: "OFFICIAL_ANALOGUE",
    verifiedAt: "2026-08-29",
    supports: ["bounded mean/SD standardisation analogue"],
    notes: "Official for PGP only. UG use is not confirmed.",
  },
];

export const IIMB_UG_ASSUMPTIONS = [
  "The site's 38.4% Class X overall planning filter is a user-requested assumption, not an IIMB rule. The cycle-specific procedure says at least 60% in Class X, while the programme pages specify at least 60% in Class X Mathematics.",
  "Canonical +3/−1 scores are an exact three-times representation of the confirmed +1/−1/3 marking scheme.",
  "The historical table's aggregate 114 is treated as a canonical raw-score floor because it cannot be a percentile.",
  "Linear raw-to-weighted test conversion is a transparent planning model, not IIMB's confirmed conversion.",
  "The PGP mean/SD standardisation formula is an official analogue only; UG normalization is not published.",
  "Gender-diversity points are inferred from the selected gender using the bundled policy-eligible categories.",
  "The current interview-call cutoff is unknown.",
  "When the current cutoff is unavailable, the interview-call verdict uses transparent Pre-PI planning bands: 80+ strong, 70–79.99 competitive, 60–69.99 borderline, and below 60 unlikely.",
  "Interview-call probability remains disabled until defensible multi-cycle calibration data exists.",
] as const;
